### ISSUE TITLE
TOO slow inference speed

### ISSUE THREAD

**Issue by Zhentao-Liu** [hyn2028/tpdm#5]
I am testing the code run_tpdm_svct.py, it needs almost 15 hours for a single case (batchsize=8 A10080G). It's too slow, any methods to accelerate?

**Comment by Zhentao-Liu** [comment]
Today I get the inference results. However its really poor. The reference volume and recon volume are shown as bellow (in nii.gz format, 3D Slicer). I use the following command.

python run_tpdm_svct.py ./dataset_sample/BMR_256_synthetic_0 5 --sv-sparsity=20
dps weight=5, it takes me about 15 hours to finish the inference process, any suggestions? anything wrong? especially for the dps weight. 
I am a new follower of diffusion, and I dont know much about that.

![ref](https://github.com/hyn2028/tpdm/assets/81148025/ab0e54b5-bf5d-4d68-a7c0-c4f406f87b27)
![recon](https://github.com/hyn2028/tpdm/assets/81148025/830b5037-a4a1-4eaa-8450-04b1dea509e7)

**Comment by hyn2028** [comment]
Hello, @Zhentao-Liu. First, thank you for your interest in our research.

It is normal for the reconstruction time to take as long as you mentioned. Diffusion sampling and inverse problem solving acceleration techniques were not applied in this study. Therefore, it is slow because it uses a total of 2000 diffusion steps.

In the case of the result, it is assumed to be caused by incorrectly set dps_weight. There is no general way to determine that value; it must be determined experimentally. If the dps_weight value is too small, the generated result will not follow the measurement, and if it is too large, the result will be ruined like in your case.

Since the SV-CT experiment was performed on the CT dataset and model in the paper, please understand that unlike MR-ZSR and CS-MRI, we do not have an optimal dps_weight for that data set and task combination.

**Comment by Zhentao-Liu** [comment]
Thank you for your reply. I will try adjusting the DPS weight later. Anyway, I want to perform sparse-view CT reconstruction, but the checkpoint you provided seems to be for MR-ZSR. Does it matter for the poor reconstruction results? Also, do you have any suggestions for acceleration? It is too slow.

**Comment by hyn2028** [comment]
Checkpoints must match the domain of the measurement dataset. While some degree of contrast difference between datasets is acceptable, using CT measurement data for MRI checkpoints can lead to very bad results.

Speedup is a research topic in itself, and unfortunately, there is no simple way to accelerate with the current methodology. Applying various diffusion sampling and inverse problem-solving acceleration techniques may help, but there is no straightforward and effective way.

**Comment by Zhentao-Liu** [comment]
So you mean you provided ckpt DO NOT support SVCT problem? And how do you train your model, ragarding it's so time consuming. How many and what type of GPU cards did you use?

**Comment by Zhentao-Liu** [comment]
May DDS[https://github.com/HJ-harry/DDS] help for acceleration?

**Comment by hyn2028** [comment]
We apologize for the long wait. Checkpoints and sample volumes related to LDCT-CUBE which was used in our paper have just been released, please see the updated README. 

However, The LDCT-CUBE checkpoint originated from an experiment to observe the behavior of TPDM when the dataset was extremely small (10 volumes) to train a 3D model. Therefore, its performance may be insufficient for use in abdominal CT-related tasks.

**Comment by hyn2028** [comment]
The training processes of the TPDM were executed utilizing two NVIDIA GeForce RTX 3090 GPUs. Employing the settings expounded upon in the text, the training duration for the MRI and CT models amounted to approximately 3 days and 1 day, respectively, for each 2D model, be it primary or auxiliary.
